services:
  app:
    container_name: conversational-ai
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    network_mode: host
    env_file:
      - .env
    volumes:
      - ../src:/app/src/
  
  opensips:
    container_name: opensips-conv-ai
    image: opensips/opensips:latest
    volumes:
      - ../cfg/:/etc/opensips/
    network_mode: host
