services:
  opensips:
    container_name: ai-voice-connector-opensips
    build:
      context: ../
      dockerfile: ./docker/docker-opensips/Dockerfile
      args:
        OPENSIPS_VERSION: 3.5  # Ou qualquer outra versão/tag válida do GitHub
    ports:
      - "5060:5060"
    volumes:
      - ../cfg/:/usr/local/opensips/etc/opensips/

  engine:
    container_name: ai-voice-connector-engine
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "50060:50060"
      - "8080:8080"
    environment:
      CONFIG_FILE: /app/src/config.ini
    env_file:
      - .env
    volumes:
      - ../src:/app/src/